language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pipenv
  - pip install masonite-cli
  - pipenv install --no-lock
  - craft key --store
script: python -m pytest
