version: 2.1
jobs:
    build:
      docker:
        - image: circleci/python:3.6  # primary container for the build job
      steps:
        - checkout
        - run: make
        - run: make ci
    python34:
      docker:
        - image: circleci/python:3.4
      steps:
        - checkout
        - run: make
        - run: make ci
    python35:
      docker:
        - image: circleci/python:3.5
      steps:
        - checkout
        - run: make
        - run: make ci
    python37:
      docker:
        - image: circleci/python:3.7
      steps:
        - checkout
        - run: make
        - run: make ci
    MasoniteValidation:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - run: python trigger_build.py --repo masoniteframework/validation --branch circle-ci --build MASONITE_DEPENDENT_BRANCH=$CIRCLE_BRANCH
    MasoniteAPI:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - run: python trigger_build.py --repo masoniteframework/api --branch 2.2 --build BUILD_BRANCH=$CIRCLE_BRANCH
    CodeCoverage:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - run: pip install -r requirements.txt --user
        - run: make coverage
        - run: make deepsource

orbs:
    masonite: masonite/trigger@dev:latest

workflows: 
  version: 2
  build_and_test:
    jobs: 
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - python34:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - python35:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - python37:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - MasoniteValidation:
          requires:
              - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - MasoniteAPI:
          requires:
              - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - CodeCoverage:
          requires:
              - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - deploy:
          requires:
            - MasoniteValidation
            - MasoniteAPI
            - CodeCoverage
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
